name: flash_chat
description: A texting app that use Firebase as database for user registeration and authentication 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2

  animated_text_kit: ^2.5.1
  rflutter_alert: ^1.1.0
  modal_progress_hud: ^0.1.3

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
